# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fast_check',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
