# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fast_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fast_check_users', to='member.FastCheck'),
        ),
    ]
