# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170302_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='fast_check',
        ),
        migrations.AlterField(
            model_name='fastcheck',
            name='click',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fastcheck_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
