# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170302_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastcheck',
            name='click',
        ),
        migrations.AddField(
            model_name='myuser',
            name='fast_check',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='FastCheck',
        ),
    ]
